name: Petstore API tests

on:
  workflow_dispatch

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm cit
      - name: Send results and generate allure report
        uses: Xotabu4/send-to-allure-server-action@1
        if: ${{always() }}
        with:
          allure-server-url: 'http://93.126.97.71:5001/'
